name: machine-learning
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3
  - pip
  - jupyter
  - jupyter_nbextensions_configurator
  - matplotlib
  - nltk
  - pandas
  - pillow
  - scikit-learn
  - spacy
  - pip:
    - joblib
    - jupyter-tabnine
    - mglearn
    - python-language-server
    - pyls
    - six

